version: '3'
services:
  client:
    image: "ruru0403/fib-client"
    mem_limit: 128m
    hostname: client # 創建 hostname，可以被其他服務使用，例如 nginx 中的 http://client，在 AWS 中要先 specify
  server:
    image: "ruru0403/fib-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres 
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "ruru0403/fix-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "ruru0403/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"